# Generated by Django 4.2 on 2023-04-27 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authors',
            old_name='task',
            new_name='bio',
        ),
    ]
