# Generated by Django 4.2 on 2023-04-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
