# Generated by Django 4.2 on 2023-04-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_authors_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='about_img')),
            ],
        ),
        migrations.AlterField(
            model_name='authors',
            name='photo',
            field=models.ImageField(upload_to='authors_img'),
        ),
    ]
