# Generated by Django 4.2 on 2023-04-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_about_alter_authors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors_img'),
        ),
    ]
