# Generated by Django 4.2 on 2023-05-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_authors_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='bio',
            field=models.TextField(default=None, verbose_name='Біографія'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='photo',
            field=models.ImageField(default=2, upload_to='authors_img'),
            preserve_default=False,
        ),
    ]
