# Generated by Django 4.2 on 2023-05-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
